# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f522e7da0fc9e453be9c43f9ba0bf9ae641d970c18c40c771f5b085f50ec2d12aafef71dd91efd7037f77d1781f055462530af0c17d609a0f6f2efd8ef6d341

test:
  secret_key_base: 1b7df7265d456c6f60343542e26144435ac1fbf9320f1d7db9eddea8b21cc163ccdfbc825ccba9cd1ac05f097e06764c20c399eb885e46487fb02a1f5cfe874f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
